package com.amumtrade.handler;

import java.util.ArrayList;
import java.util.List;

public class AmumTest {
	public static List<String> topGainerList = new ArrayList<String>();
	public static List<String> concurrentGainerList = new ArrayList<String>();
	public static void main(String[] args) {
		addTopGainer();
		addConcurrentGainerList();
		for(String name : concurrentGainerList){
			if(!topGainerList.contains(name)){
				System.out.println(name);
			}
			
		}
		System.out.println("Completed.....");
	}
	private static void addConcurrentGainerList() {
		concurrentGainerList.add("Mohit Ind");
		concurrentGainerList.add("Bombay Burmah");
		concurrentGainerList.add("Simplex Infra");
		concurrentGainerList.add("Manaksia");
		concurrentGainerList.add("KSE");
		concurrentGainerList.add("Honeywell Autom");
		concurrentGainerList.add("Accel Frontline");
		concurrentGainerList.add("Global Offshore");
		concurrentGainerList.add("Themis Medicare");
		concurrentGainerList.add("FIEM Ind");
		concurrentGainerList.add("Texmaco Rail");
		concurrentGainerList.add("Orient Refract");
		concurrentGainerList.add("Onward Tech");
		concurrentGainerList.add("Man Industries");
		concurrentGainerList.add("Redington");
		concurrentGainerList.add("JMC Projects");
		concurrentGainerList.add("Hindalco");
		concurrentGainerList.add("Eveready Ind");
		concurrentGainerList.add("Ahmednagar Forg");
		concurrentGainerList.add("Zuari Global");
		concurrentGainerList.add("Zicom Security");
		concurrentGainerList.add("Cairn India");
		concurrentGainerList.add("eClerx Services");
		concurrentGainerList.add("Blue Star Info");
		concurrentGainerList.add("Pidilite Ind");
		concurrentGainerList.add("Panoramic Uni");
		concurrentGainerList.add("Aban Offshore");
		concurrentGainerList.add("J Kumar Infra");
		concurrentGainerList.add("Welspun India");
		concurrentGainerList.add("ICICI Bank");
		concurrentGainerList.add("Advanta");
		concurrentGainerList.add("ALSTOM India");
		concurrentGainerList.add("Castrol");
		concurrentGainerList.add("Guj State Petro");
		concurrentGainerList.add("Ruby Mills");
		concurrentGainerList.add("EIH Assoc Hotel");
		concurrentGainerList.add("Talbros Auto");
		concurrentGainerList.add("Nilkamal");
		concurrentGainerList.add("Star Ferro");
		concurrentGainerList.add("SKF India");
		concurrentGainerList.add("Surya Roshni");
		concurrentGainerList.add("Ruchira Papers");
		concurrentGainerList.add("Vipul");
		concurrentGainerList.add("SRS");
		concurrentGainerList.add("aurionPro Sol");
		concurrentGainerList.add("Rupa and Comp");
		concurrentGainerList.add("Adani Ports");
		concurrentGainerList.add("Oracle Fin Serv");
		concurrentGainerList.add("Sabero Organics");
		concurrentGainerList.add("EngineersInd");
		
	}
	private static void addTopGainer() {

		topGainerList.add("Accel Frontline");
		topGainerList.add("Oswal Minerals");
		topGainerList.add("KSE");
		topGainerList.add("Neo Corp");
		topGainerList.add("Simplex Project");
		topGainerList.add("Crompton Greave");
		topGainerList.add("Alicon Castallo");
		topGainerList.add("Hindalco");
		topGainerList.add("Alphageo");
		topGainerList.add("OM Metals Infra");
		topGainerList.add("MTNL");
		topGainerList.add("Amtek India");
		topGainerList.add("Salona Cotspin");
		topGainerList.add("Jindal Saw");
		topGainerList.add("Rajesh Exports");
		topGainerList.add("Persistent");
		topGainerList.add("Honeywell Autom");
		topGainerList.add("FIEM Ind");
		topGainerList.add("Rane Holdings");
		topGainerList.add("Bharat Elec");
		topGainerList.add("Hanung Toys");
		topGainerList.add("SAIL");
		topGainerList.add("RPP Infra Proj");
		topGainerList.add("JSW Energy");
		topGainerList.add("Kirloskar Oil");
		topGainerList.add("Snowman Logist");
		topGainerList.add("Deep Industries");
		topGainerList.add("Manaksia");
		topGainerList.add("Esab India");
		topGainerList.add("PNB Gilts");
		topGainerList.add("Simplex Casting");
		topGainerList.add("Seamec");
		topGainerList.add("Atul Auto");
		topGainerList.add("Maan Aluminium");
		topGainerList.add("Atlas Cycles");
		topGainerList.add("Wockhardt");
		topGainerList.add("KNR Construct");
		topGainerList.add("Welspun India");
		topGainerList.add("Federal-Mogul");
		topGainerList.add("Bharat Rasayan");
		topGainerList.add("Amtek Auto");
		topGainerList.add("KCP Sugar");
		topGainerList.add("VTM");
		topGainerList.add("Ahmednagar Forg");
		topGainerList.add("Omkar Special");
		topGainerList.add("Vardhman Hold");
		topGainerList.add("Amara Raja Batt");
		topGainerList.add("Elecon Eng");
		topGainerList.add("Balmer Lawrie");
		topGainerList.add("Patel Integrate");
		topGainerList.add("Edelweiss");
		topGainerList.add("Pilani Invest");
		topGainerList.add("TV TodayNetwork");
		topGainerList.add("V-Guard Ind");
		topGainerList.add("SIL Invest");
		topGainerList.add("Cairn India");
		topGainerList.add("Sreeleathers");
		topGainerList.add("Banaras Beads");
		topGainerList.add("Redington");
		topGainerList.add("Hind Zinc");
		topGainerList.add("IVP");
		topGainerList.add("Lakshmi Mills");
		topGainerList.add("Tata Comm");
		topGainerList.add("Maral Overseas");
		topGainerList.add("Mahindra CIE");
		topGainerList.add("Rain Industries");
		topGainerList.add("UPL");
		topGainerList.add("Indiabulls Hsg");
		topGainerList.add("GSS Infotech");
		topGainerList.add("eClerx Services");
		topGainerList.add("Themis Medicare");
		topGainerList.add("Suprajit Eng");
		topGainerList.add("ALLSEC Tech");
		topGainerList.add("Siemens");
		topGainerList.add("Sah Petroleums");
		topGainerList.add("Tara Jewels");
		topGainerList.add("Delta Corp");
		topGainerList.add("Visaka Ind");
		topGainerList.add("Den Networks");
		topGainerList.add("Eveready Ind");
		topGainerList.add("J Kumar Infra");
		topGainerList.add("Vipul");
		topGainerList.add("MBL Infra");
		topGainerList.add("Ashoka Buildcon");
		topGainerList.add("Banco Products");
		topGainerList.add("Zee Entertain");
		topGainerList.add("Dishman Pharma");
		topGainerList.add("ICICI Bank");
		topGainerList.add("Orient Refract");
		topGainerList.add("City Union Bank");
		topGainerList.add("Renaissance Jew");
		topGainerList.add("Bharat Forge");
		topGainerList.add("Balrampur Chini");
		topGainerList.add("Castrol");
		topGainerList.add("Century Enka");
		topGainerList.add("aurionPro Sol");
		topGainerList.add("Pidilite Ind");
		topGainerList.add("Time Techno");
		topGainerList.add("Essel Propack");
		topGainerList.add("Avanti Feeds");
		topGainerList.add("Colgate");
		topGainerList.add("Ambika Cotton");
		topGainerList.add("Orbit Exports");
		topGainerList.add("Aban Offshore");
		topGainerList.add("Voltamp Trans");
		topGainerList.add("Vardhman Poly");
		topGainerList.add("Finolex Cables");
		topGainerList.add("Swelect Energy");
		topGainerList.add("Adani Power");
		topGainerList.add("Lumax Auto Tech");
		topGainerList.add("Man Industries");
		topGainerList.add("Sun TV Network");
		topGainerList.add("Godfrey Phillip");
		topGainerList.add("Elgi Equipments");
		topGainerList.add("IGL");
		topGainerList.add("Mohit Ind");
		topGainerList.add("V-Mart Retail");
		topGainerList.add("WABCO India");
		topGainerList.add("Nilkamal");
		topGainerList.add("Mah Scooters");
		topGainerList.add("Godawari Power");
		topGainerList.add("Indraprastha");
		topGainerList.add("Vesuvius India");
		topGainerList.add("M&M Financial");
		topGainerList.add("Guj Gas");
		topGainerList.add("SKF India");
		topGainerList.add("REC");
		topGainerList.add("Ramco Cements");
		topGainerList.add("Plastiblends");
		topGainerList.add("Rupa and Comp");
		topGainerList.add("Surya Roshni");
		topGainerList.add("Sunflag Iron");
		topGainerList.add("Vimal Oils");
		topGainerList.add("Ganesh Housing");
		topGainerList.add("India Cements");
		topGainerList.add("Repro India");
		topGainerList.add("Geometric");
		topGainerList.add("NALCO");
		topGainerList.add("Technofab Engg");
		topGainerList.add("Alkyl Amines");
		topGainerList.add("CESC");
		topGainerList.add("Indiabulls Real");
		topGainerList.add("Adani Ports");
		topGainerList.add("Patel Eng");
		topGainerList.add("Munjal Auto Ind");
		topGainerList.add("Tata Coffee");
		topGainerList.add("Balaji Amines");
		topGainerList.add("Shemaroo Ent");
		topGainerList.add("Godrej Ind");
		topGainerList.add("MOIL");
		topGainerList.add("Wendt");
		topGainerList.add("Zicom Security");
		topGainerList.add("Chambal Fert");
		topGainerList.add("Asian Hotel (E)");
		topGainerList.add("Capital First");
		topGainerList.add("TIL");
		topGainerList.add("Godrej Consumer");
		topGainerList.add("JSW Holdings");
		topGainerList.add("Hercules Hoists");
		topGainerList.add("Gujarat Pipavav");
		topGainerList.add("Bajaj Corp");
		topGainerList.add("Goa Carbon");
		topGainerList.add("Oil India");
		topGainerList.add("IDBI Bank");
		topGainerList.add("Mercator");
		topGainerList.add("HSIL");
		topGainerList.add("Pfizer");
		topGainerList.add("Guj State Petro");
		topGainerList.add("SRS");
		topGainerList.add("Tata Chemicals");
		topGainerList.add("Indian Card");
		topGainerList.add("Ruchira Papers");
		topGainerList.add("Abbott India");
		topGainerList.add("Advanta");
		topGainerList.add("Ind Motor Parts");
		topGainerList.add("ALSTOM India");
		topGainerList.add("Mayur Uniquoter");
		topGainerList.add("Hitachi Home");
		topGainerList.add("Jamna Auto");
		topGainerList.add("Shilpa");
		topGainerList.add("Jocil");
		topGainerList.add("Zodiac Clothing");
		topGainerList.add("Cigniti Tech");
		topGainerList.add("AIA Engineering");
		topGainerList.add("Alembic Pharma");
		topGainerList.add("Nitin Fire Prot");
		topGainerList.add("Whirlpool");
		topGainerList.add("Uttam Galva");
		topGainerList.add("Bharat Gears");
		topGainerList.add("Gyscoal Alloys");
		topGainerList.add("Godrej Prop");
		topGainerList.add("Bhartiya Inter");
		topGainerList.add("Power Finance");
		topGainerList.add("Sonata");
		topGainerList.add("Tide Water Oil");
		topGainerList.add("Lakshmi Machine");
		topGainerList.add("Container Corp");
		topGainerList.add("NMDC");
		topGainerList.add("MRF");
		topGainerList.add("Magma Fincorp");
		topGainerList.add("CenturyPlyboard");
		topGainerList.add("Tantia Const");
		topGainerList.add("Eimco Elecon");
		topGainerList.add("Aurobindo Pharm");
		topGainerList.add("Balkrishna Ind");
		topGainerList.add("Pratibha Ind");
		topGainerList.add("Tube Investment");
		topGainerList.add("GIC Housing Fin");
		topGainerList.add("Tokyo Plast");
		topGainerList.add("Talbros Auto");
		topGainerList.add("Supreme Ind");
		topGainerList.add("Subros");
		topGainerList.add("Bajaj Holdings");
		topGainerList.add("PTL Enterprises");
		topGainerList.add("Sanofi India");
		topGainerList.add("Globus Spirits");
		topGainerList.add("NTPC");
		topGainerList.add("Vardhman Text");
		topGainerList.add("Butterfly");
		topGainerList.add("KPIT Tech");
		topGainerList.add("Coromandel Int");
		topGainerList.add("Can Fin Homes");
		topGainerList.add("Kesar Terminals");
		topGainerList.add("Jindal Drilling");
		topGainerList.add("Honda Siel");
		topGainerList.add("Alchemist");
		topGainerList.add("CARE");
		topGainerList.add("Aptech");
		topGainerList.add("Emco");
		topGainerList.add("Torrent Pharma");
		topGainerList.add("Rel Capital");
		topGainerList.add("Texmaco Rail");
		topGainerList.add("Polaris Tech");
		topGainerList.add("Guj Ind Power");
		topGainerList.add("EngineersInd");
		topGainerList.add("Just Dial");
		topGainerList.add("Rel Ind Infra");
		topGainerList.add("EIH Assoc Hotel");
		topGainerList.add("Premier");
		topGainerList.add("Neyveli Lignite");
		topGainerList.add("Prakash Ind");
		topGainerList.add("PTC India");
		topGainerList.add("Zandu Realty");
		topGainerList.add("NCC");
		topGainerList.add("IDFC");
		topGainerList.add("Star Ferro");
		topGainerList.add("IIFL Holdings");
		topGainerList.add("Asahi Songwon");
		topGainerList.add("Blue Star Info");
		topGainerList.add("Brigade Ent");
		topGainerList.add("Diamond Power");
		topGainerList.add("Grindwell Norto");
		topGainerList.add("Ruby Mills");
		topGainerList.add("Pearl Global In");
		topGainerList.add("Nandan Denim");
		topGainerList.add("Balaji Telefilm");
		topGainerList.add("KEC Intl");
		topGainerList.add("8K Miles Soft");
		topGainerList.add("Hatsun Agro");
		topGainerList.add("SE Investments");
		topGainerList.add("Sterlite Techno");
		topGainerList.add("Kewal Kiran");
		topGainerList.add("ADF Foods");
		topGainerList.add("Orient Abrasive");
		topGainerList.add("Nelcast");
		topGainerList.add("RamkrishnaForge");
		topGainerList.add("Granules India");
		topGainerList.add("L&T Finance");
		topGainerList.add("TVS Motor");
		topGainerList.add("Flexituff Intl");
		topGainerList.add("Talwalkars Fitn");
		topGainerList.add("JMC Projects");
		topGainerList.add("Oracle Fin Serv");
		topGainerList.add("Eicher Motors");
		topGainerList.add("Jaiprakash Asso");
		topGainerList.add("Transformers");
		topGainerList.add("Mcleod");
		topGainerList.add("DB (Int) Stock");
		topGainerList.add("Sabero Organics");
		topGainerList.add("Jyoti Structure");
		topGainerList.add("Cholamandalam");
		topGainerList.add("Ratnamani Metal");
		topGainerList.add("Kabra Extrusion");
		topGainerList.add("Gallantt Ispat");
		topGainerList.add("ICRA");
		topGainerList.add("Marksans Pharma");
		topGainerList.add("Bajaj Auto");
		topGainerList.add("Valecha Engg");
		topGainerList.add("Kirloskar Ind");
		topGainerList.add("IFB Agro");
		topGainerList.add("Hexaware Tech");
		topGainerList.add("TTK Prestige");
		topGainerList.add("Max India");
		topGainerList.add("Bosch");
		topGainerList.add("Welspun Ent");
		topGainerList.add("Guj Alkali");
		topGainerList.add("Infinite Comp");
		topGainerList.add("BEML");
		
	}

}
